spring:
  profiles:
    active: local
  banner:
    location: banner.txt
  application:
    name: CONNECTION-SERVICE

# Server configuration
server:
  port: 8082
  servlet:
    context-path: /connection

# Logging configuration
logging:
  level:
    org.springframework.security: DEBUG
    com:
      connection:
        securityConfig: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
databyte:
  security:
    api-matcher:
     - /**
    abstract-endpoints:
     - /swagger-ui.html
    permitted-endpoints:
      - /v1/**
      - /api/v1/auth/user/create
      - /api/v1/auth/login
      - /error
    allowed-origins:
      - http://localhost:3000
      - http://localhost:4200
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE"
    allowed-headers:
      - Authorization
      - Content-Type
      - Accept
    allow-credentials: true
