spring:
  profiles:
    active: dev
  banner:
    location: banner.txt
  application:
    name: CONNECTION-SERVICE

# Server configuration
server:
  port: 8082
  servlet:
    context-path: /connection

# DataByte Configuration
databyte:
  context-path: /connection
  api-domain: http://localhost:8082
  ui-domain: http://localhost:4300
  security:
    api-matcher:
      - "/**"
    abstract-endpoints:
      - "/swagger-ui.html"
    permitted-endpoints:
      - "/v1/**"
      - "/api/v1/auth/user/create"
      - "/api/v1/auth/login"
      - "/error"
    allowed-origins:
      - "http://localhost:3000"
      - "http://localhost:4200"
      - "http://localhost:4300"
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
    allowed-headers:
      - "Authorization"
      - "Content-Type"
      - "Accept"
    allow-credentials: true
