spring:
  datasource:
    url: jdbc:postgresql://pg-8de9f12-data-byte.h.aivencloud.com:19243/defaultdb
    username: avnadmin
    password: AVNS_4cb5tvyoy_Jow90vRr2
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: connection_service

  liquibase:
    enabled: true
    change-log: classpath:database/changelog-master.xml
    default-schema: ${spring.jpa.properties.hibernate.default_schema}

eureka:
  instances:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
